### ISSUE TITLE
One node-rolling-spider

### ISSUE THREAD

**Issue by voodootikigod** [ChrisTheBaron/node-rolling-spider#2]
Any reason we couldn't collapse this library's changes with the original library so there is only one library we are all working and benefitting from?

**Comment by ChrisTheBaron** [comment]
Hey,

No, there is no reason why we could not do that. As long as everyone is happy with the changes I've made. When I get a moment I'll make a branch on my repo to bring the documentation back in-line with the original repo and create a PR.

Cheers, Chris

**Comment by voodootikigod** [comment]
I have a couple other items but I can rebase on to yours.

On Thursday, April 30, 2015, Chris Taylor notifications@github.com wrote:

> Hey,
> 
> No, there is no reason why we could not do that. As long as everyone is
> happy with the changes I've made. When I get a moment I'll make a branch on
> my repo to bring the documentation back in-line with the original repo and
> create a PR.
> 
> Cheers, Chris
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ChrisTheBaron/node-rolling-spider/issues/2#issuecomment-97669085
> .

## 

_Chris Williams_

@voodootikigod http://twitter.com/voodootikigod | GitHub
http://github.com/voodootikigod

_The things I make that you should check out:_
SaferAging http://www.saferaging.com/ | JSConf http://jsconf.com/ |
RobotsConf http://robotsconf.com/ | RobotsWeekly
http://robotsweekly.com/

Help me end the negativity on the internet, share this
http://jsconf.eu/2011/an_end_to_negativity.html.

**Comment by ChrisTheBaron** [comment]
Hey, 

Okay just let me know what I have to do. Unfortunately the earliest I will be able to do anything major is next Monday. But I can do something quickly tomorrow morning. 

Cheers, Chris

**Comment by voodootikigod** [comment]
I can handle it and just review the PR/final

_Chris Williams_

@voodootikigod http://twitter.com/voodootikigod | GitHub
http://github.com/voodootikigod

_The things I make that you should check out:_
SaferAging http://www.saferaging.com/ | JSConf http://jsconf.com/ |
RobotsConf http://robotsconf.com/ | RobotsWeekly
http://robotsweekly.com/

Help me end the negativity on the internet, share this
http://jsconf.eu/2011/an_end_to_negativity.html.

**Comment by voodootikigod** [comment]
v. 1.0.0 has been released with your codeset merged in and attribution. Can you please remove parrot-rolling-spider from npm to reduce confusion.

Thank you,

**Comment by ChrisTheBaron** [comment]
Hey, 

Thank you for merging it in. I'm afraid I cannot remove it as another one of my packages, 'cylon-rolling-spider', depends on it. I will deprecate it and update my other package to use the centralised version.

Cheers, Chris

**Comment by voodootikigod** [comment]
That works.

_Chris Williams_
